apiVersion: v1
kind: ServiceAccount
metadata:
  name: serving-controller
  namespace: controller-ns

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: serving-controller
rules:
  - apiGroups:
      - serving.knative.dev
    resources:
      - '*'
    verbs:
      - get
      - list
      - create
      - watch
      - patch
      - delete
      - update

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: serving-controller-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: serving-controller
subjects:
  - kind: ServiceAccount
    name: serving-controller
    namespace: controller-ns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serving-controller
  namespace: controller-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: revisoin-controller
  template:
    metadata:
      labels:
        app: revisoin-controller
    spec:
      serviceAccountName: serving-controller
      containers:
      - name: controller
        image: registry.cn-hangzhou.aliyuncs.com/knative-sample/serving-controller:master_48057fa5-20190828172305
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 100Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
